### ISSUE TITLE
上传失败：fastlane finished with errors

### ISSUE THREAD

**Issue by kaelinda** [FIRHQ/fastlane-plugin-fir_cli#15]
```
Traceback (most recent call last):
        41: from /usr/local/bin/fastlane:23:in `<main>'
        40: from /usr/local/bin/fastlane:23:in `load'
        39: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
        38: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        35: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        33: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        32: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        31: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'

        28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        23: from Fastfile:40:in `block (2 levels) in parsing_binding'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-fir_cli-2.0.9/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:39:in `run'
        14: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.9/lib/fir/util/publish.rb:10:in `publish'
        13: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.9/lib/fir/util/publish.rb:267:in `initialize_publish_options'
        12: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.9/lib/fir/util.rb:36:in `fetch_user_info'
        11: from /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:10:in `block (2 levels) in <module:DefaultRe
stModule>'
10: from /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
         9: from /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
         8: from /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
         7: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
         6: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
         5: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
         4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
         2: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
         1: from /Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 401 Unauthorized (RestClie
nt::Unauthorized)
```

**Comment by kaelinda** [comment]
sorry  是 api_token变了
