### ISSUE TITLE
wxwork_access_token不传时流程无法正常结束

### ISSUE THREAD

**Issue by Yigang0622** [FIRHQ/fastlane-plugin-fir_cli#26]
当ipa上传完成后
```
I, [2021-04-21T00:22:05.183053 #44002]  INFO -- : Updating app info......
I, [2021-04-21T00:22:11.097022 #44002]  INFO -- : Fetch app info from fir.im
I, [2021-04-21T00:22:16.229463 #44002]  INFO -- : end upload
I, [2021-04-21T00:22:16.229581 #44002]  INFO -- : ✈ -------------------------------------------- ✈
I, [2021-04-21T00:22:16.229630 #44002]  INFO -- : Published succeed: http://d.firim.pro/listify
```
会报一个关于wxwork_notifier函数的错误，导致流程无法走完。
```
3: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.12/lib/fir/util/publish.rb:36:in `publish'
2: from /Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.12/lib/fir/util/publish.rb:226:in `wxwork_notifier'
1: from /Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:19:in `block (2 levels) in <module:DefaultRestModule>'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.1/lib/api_tools/default_rest_module.rb:75:in `basic_request': [!] undefined method `body' for nil:NilClass (NoMethodError)
```
https://github.com/FIRHQ/fir-cli/blob/5626a5ff488559375dab48013e4810dd3f819b7b/lib/fir/util/publish.rb#L209
wx_notifier函数中存在以下逻辑
```
webhook_url = options[:wxwork_webhook]
webhook_url ||= "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=#{options[:wxwork_access_token]}"
return if webhook_url.blank?
```
当wxwork_webhook为nil的时候会走wxwork_access_token逻辑
所以需要将默认的wxwork_webhook参数设置为""，使wx_notifier终止
并且当wxwork_access_token存在时wxwork_webhook必须为nil

**Comment by Yigang0622** [comment]
已提PR修复该问题 #27

**Comment by jicheng1014** [comment]
跪谢

**Comment by jicheng1014** [comment]
已在  fir-cli 中修复此问题
